spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssm?serverTimezone=GMT
    username: root
    password: root123
    tomcat:
      max-active: 50
      max-wait: 30000
      initial-size: 5
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: mapper/*.xml
  type-aliases-package: com.fayayo.pojo